title = "Server Panic"
baseURL = 'https://serverpanic.org/'

# This is what goes in <html lang="">
languageCode = 'es-mx'

theme = "hugo-blog-awesome"

# This defines how dates are formatted
defaultContentLanguage = "es-mx"

# To enable Google Analytics 4 (gtag.js) provide G-MEASUREMENT_ID below.
# To disable  Google Analytics, simply leave the field empty or remove the next line
googleAnalytics = '' # G-MEASUREMENT_ID


# Enable emojis globally
enableEmoji = true

# set markup.highlight.noClasses=false to enable code highlight
[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true

[menu]
  [[menu.main]] 
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Inicio'
    url = '/'
    weight = 10
  [[menu.main]]
    pageRef="posts"
    name = 'Articulos'
    url = '/posts/'
    weight = 20
  [[menu.main]]
    pageRef="about"
    name = 'Acerca de'
    url = '/about/'
    weight = 30

[params]
  sitename = "Server Panic"
  defaultColor = "dark" # set color mode: dark, light, auto
  # Setting it to 'auto' applies the color scheme based on the visitor's device color preference.If you don't specify anything, ignore this parameter, or leave it blank, 
  # the default value is set to 'auto'. 
  # You can take a look at layouts/index.html for more information.
  description = "Blog de tecnología, administración de sistemas y programación"
  mainSections = ['posts']

[params.author]
  avatar = "avatar.jpg" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "Servidor en pánico"
  name = "Miguel A Reynoso"
  description = "Mantenga la calma y use software libre"

[[params.socialIcons]]
name = "github"
url = "https://github.com/c411n"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/c41n5"

[[params.socialIcons]]
name = "Rss"
url = "index.xml"
